(()=>{const rows=[
{jp:"気分がいい",kana:"きぶんがいい",zh:"心情好；状态不错",level:"N3/生活",scene:"说自己的心情、精神状态很好。",ex:"今日は天気もいいし、気分がいい。",exKana:"きょうは てんきも いいし、きぶんが いい。",exZh:"今天天气也不错，心情很好。",spoken:"今日、なんか気分いい。",confuse:"気持ちいい偏身体/感官上的舒服；気分がいい偏心情或整体状态。"},
{jp:"気持ちいい",kana:"きもちいい",zh:"舒服；爽",level:"N3/生活",scene:"天气、风、洗澡、按摩、运动后等感官舒服。",ex:"今日の風は気持ちいいね。",exKana:"きょうの かぜは きもちいいね。",exZh:"今天的风吹着真舒服啊。",spoken:"めっちゃ気持ちいい。",confuse:"不要直接当成“心情好”；表达心情好更常用気分がいい。"},
{jp:"気持ち悪い／きもい",kana:"きもちわるい／きもい",zh:"恶心；不舒服／好恶心、好膈应",level:"生活口语",scene:"気持ち悪い可说身体不适或恶心；きもい是很口语的缩略说法，语气更直接。",ex:"ちょっと気持ち悪いから、少し休む。",exKana:"ちょっと きもちわるいから、すこし やすむ。",exZh:"我有点不舒服，休息一下。",spoken:"うわ、きもい！",confuse:"きもい不是“心情不好”。它来自気持ち悪い，对人说可能很失礼。"},
{jp:"気にしないで",kana:"きにしないで",zh:"别在意；没关系",level:"N3/生活",scene:"别人道歉、担心给你添麻烦时安慰对方。",ex:"大丈夫。気にしないで。",exKana:"だいじょうぶ。きにしないで。",exZh:"没事，别在意。",spoken:"全然気にしないで。",confuse:"気にする＝在意；気になる＝在意/挂心/引起注意，两者用法不同。"},
{jp:"せっかく",kana:"せっかく",zh:"好不容易；难得",level:"N3",scene:"已经花了时间、机会或精力，所以不想浪费。",ex:"せっかく東京まで来たから、どこか遊びに行こう。",exKana:"せっかく とうきょうまで きたから、どこか あそびに いこう。",exZh:"好不容易都来东京了，去哪里玩一下吧。",spoken:"せっかくだし、行こうよ。",confuse:"常和～のに搭配表示“好不容易……却……”，也常用せっかくだから／せっかくだし。"},
{jp:"しょうがない／仕方がない",kana:"しょうがない／しかたがない",zh:"没办法；没辙",level:"N3/生活",scene:"事情无法改变，只能接受时。",ex:"電車が止まったなら、しょうがないね。",exKana:"でんしゃが とまったなら、しょうがないね。",exZh:"如果电车停了，那也没办法啊。",spoken:"まあ、しょうがないか。",confuse:"しょうがない更口语；仕方がない稍完整。根据语气也可能带无奈。"},
{jp:"ちなみに",kana:"ちなみに",zh:"顺便说一下；补充一下",level:"N3/生活",scene:"在当前话题基础上补充相关信息。",ex:"ちなみに、明日は学校休み？",exKana:"ちなみに、あしたは がっこう やすみ？",exZh:"顺便问一下，明天学校放假吗？",spoken:"ちなみにさ、明日暇？",confuse:"不是表示时间顺序的“然后”；主要用于补充相关信息。"},
{jp:"とりあえず",kana:"とりあえず",zh:"总之先……；姑且先……",level:"N2/生活",scene:"暂时不决定全部细节，先做眼前的一步。",ex:"とりあえず、駅まで行こう。",exKana:"とりあえず、えきまで いこう。",exZh:"总之先去车站吧。",spoken:"とりあえず、これで。",confuse:"まず偏“首先”；とりあえず带有“其他之后再说，先这样”的临时感。"},
{jp:"なんとか",kana:"なんとか",zh:"想办法；勉强；总算",level:"N3",scene:"努力设法解决，或勉强达到某个结果。",ex:"なんとか間に合いました。",exKana:"なんとか まにあいました。",exZh:"总算赶上了。",spoken:"なんとかなるよ。",confuse:"なんとかする＝想办法解决；なんとかなる＝事情总会有办法/会解决。"},
{jp:"はっきり",kana:"はっきり",zh:"清楚地；明确地",level:"N3",scene:"声音、记忆、态度、意见等清楚明确。",ex:"自分の意見をはっきり言ったほうがいい。",exKana:"じぶんの いけんを はっきり いったほうが いい。",exZh:"最好把自己的意见明确说出来。",spoken:"はっきり言って。",confuse:"しっかり＝扎实/牢靠/认真；すっきり＝清爽/舒畅；不要混淆。"}
];
function esc(s){return String(s).replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(/\n/g," ")}
window.applyCommonJapanesePatch=function(html){if(html.includes('common-japanese-20261003'))return html;const payload=JSON.stringify(rows);const block=`<section id="common-japanese-20261003" style="max-width:980px;margin:24px auto;padding:16px"><h2>🗣️ 日本人常用表达</h2><p style="opacity:.75">真实生活口语：读音・中文・使用场景・完整例句・自然口语・易混点</p><div id="commonJapaneseCards"></div></section><script>(function(){var rows=${payload};var root=document.getElementById('commonJapaneseCards');if(!root)return;root.innerHTML=rows.map(function(x){return '<article style="margin:12px 0;padding:14px;border:1px solid rgba(127,127,127,.25);border-radius:14px"><h3 style="margin:0 0 6px">'+x.jp+' <small style="opacity:.7">（'+x.kana+'）</small></h3><div><b>中文：</b>'+x.zh+'　<small>'+x.level+'</small></div><div><b>使用场景：</b>'+x.scene+'</div><div style="margin-top:7px"><b>例句：</b>'+x.ex+'<br><span style="opacity:.72">'+x.exKana+'</span><br>→ '+x.exZh+'</div><div style="margin-top:7px"><b>自然口语：</b>'+x.spoken+'</div><div style="margin-top:7px"><b>易混／注意：</b>'+x.confuse+'</div></article>'}).join('');})();<\\/script>`;return html.replace('</main>',block+'</main>').replace('</body>',block+'</body>')};
})();