window.applyJlptListeningExamPatch=function(h){try{if(!h||h.includes('id="jlptListeningExam"'))return h;
const css=`<style>#jlptListeningExam{margin:16px 0;padding:14px;border:1px solid rgba(255,255,255,.14);border-radius:18px;background:rgba(255,255,255,.045)}#jlptListeningExam .le-row,#jlptListeningExam .le-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}#jlptListeningExam button,#jlptListeningExam select{min-height:42px}.le-q{padding:14px;margin:12px 0;border-radius:14px;background:rgba(255,255,255,.05);line-height:1.8}.le-opts button{display:block;width:100%;margin:7px 0;text-align:left}.le-meta{font-size:13px;opacity:.75}.le-hidden{display:none}.le-ok{outline:2px solid #56d38b}.le-no{outline:2px solid #ff7d7d}@media(max-width:560px){#jlptListeningExam{padding:11px}.le-actions button{flex:1}}</style>`;
h=h.replace('</head>',css+'</head>');
const js=`<script data-jlpt-listening="v1">(()=>{const Q=[
{id:'n2-task-01',l:'N2',t:'課題理解',ask:'男の人は、このあとまず何をしますか。',text:'会社で女の人と男の人が話しています。女：会議の資料、もう印刷しましたか。男：まだです。先に部長に内容を確認してもらおうと思って。女：部長は午後から外出ですよ。今なら席にいます。男：そうですか。じゃ、印刷の前に見てもらいます。',opts:['資料を印刷する','部長に資料を見せる','外出の準備をする','会議室を予約する'],a:1,why:'「印刷の前に見てもらいます」なので、まず部長に確認してもらいます。'},
{id:'n2-point-01',l:'N2',t:'ポイント理解',ask:'女の人がこの店を選んだ一番の理由は何ですか。',text:'友達二人がレストランについて話しています。男：駅前の新しい店、どうだった？ 女：料理もよかったけど、何より営業時間が長いのが助かった。仕事が遅くなっても入れるから。値段は前の店より少し高かったけどね。',opts:['料理が一番安いから','駅から一番近いから','遅い時間でも利用できるから','料理の種類が多いから'],a:2,why:'「何より営業時間が長いのが助かった」が決め手です。'},
{id:'n2-main-01',l:'N2',t:'概要理解',ask:'話し手が最も伝えたいことは何ですか。',text:'最近、仕事の効率を上げるために新しい道具を導入する会社が増えています。しかし、道具を入れただけで仕事が速くなるとは限りません。使い方を理解し、仕事の流れそのものを見直すことも必要です。',opts:['新しい道具は使わないほうがいい','道具だけでなく仕事の流れも見直す必要がある','仕事は必ず機械に任せるべきだ','会社は道具にお金をかけすぎている'],a:1,why:'「道具を入れただけではない」「流れそのものを見直す」が主張です。'},
{id:'n2-quick-01',l:'N2',t:'即時応答',ask:'最も自然な返事を選んでください。',text:'すみません、この資料、今日中に見ていただけませんか。',opts:['ええ、明日見ました','はい、できるだけ早く確認します','いいえ、見ていただきます','今日中だったそうです'],a:1,why:'依頼「見ていただけませんか」への自然な応答です。'},
{id:'n2-integrated-01',l:'N2',t:'統合理解',ask:'二人の条件に最も合う案はどれですか。',text:'旅行の予定について二人が話しています。女：私は午前中に美術館へ行きたい。午後は雨らしいから。男：僕は駅の近くで昼ご飯を食べたいな。夕方四時にはホテルに戻る必要があるよ。女：じゃ、美術館を先にして、そのあと駅の近くで食べよう。',opts:['午前に駅で食事、午後に美術館','午前に美術館、昼に駅周辺で食事、16時までに戻る','午後に美術館、夜に駅で食事','一日中ホテルにいる'],a:1,why:'午前の美術館、駅近くの昼食、16時までの帰館という条件をすべて満たします。'},
{id:'n3-task-01',l:'N3',t:'課題理解',ask:'女の人は、このあと何をしますか。',text:'店で店員と女の人が話しています。女：すみません、このシャツ、少し大きいんですが。店員：小さいサイズをお持ちします。色は同じでよろしいですか。女：はい、お願いします。',opts:['別の色を買う','小さいサイズを試す','店を出る','シャツを返すだけ'],a:1,why:'店員が小さいサイズを持ってくるので、それを試します。'},
{id:'n3-point-01',l:'N3',t:'ポイント理解',ask:'男の人はなぜ遅れますか。',text:'男の人が電話しています。すみません、電車が事故で止まっていて、別の線に乗り換えています。二十分ぐらい遅れそうです。',opts:['寝坊したから','道に迷ったから','電車の事故があったから','忘れ物をしたから'],a:2,why:'「電車が事故で止まっていて」が理由です。'},
{id:'n3-main-01',l:'N3',t:'概要理解',ask:'話の内容として最も合うものはどれですか。',text:'日本語を勉強するとき、分からない言葉を全部すぐ辞書で調べる人がいます。でも、まず前後の文から意味を考えてみると、読む力も少しずつ伸びていきます。',opts:['辞書は絶対に使ってはいけない','まず文脈から意味を考えることも大切だ','知らない言葉は覚えなくていい','読む練習より会話だけが大切だ'],a:1,why:'辞書を否定しているのではなく、先に文脈から考えることを勧めています。'},
{id:'n3-speech-01',l:'N3',t:'発話表現',ask:'この場面で何と言いますか。',text:'アルバイト先で、先に帰る同僚に声をかけます。',opts:['お疲れさまでした','いただきます','お大事にしてくださいました','失礼されます'],a:0,why:'仕事を終える同僚への自然な表現は「お疲れさまでした」です。'},
{id:'n3-quick-01',l:'N3',t:'即時応答',ask:'最も自然な返事を選んでください。',text:'明日の授業、休むかもしれない。',opts:['そうなんだ。どうしたの？','休んだことがあります','授業にしました','明日だったでしょう'],a:0,why:'相手の予定・状況を聞いて理由を尋ねる自然な応答です。'}
];const SEEN='jlptListeningExamSeenV1',WRONG='jlptListeningExamWrongV1';let seen=[],wrong=[];try{seen=JSON.parse(localStorage.getItem(SEEN)||'[]');wrong=JSON.parse(localStorage.getItem(WRONG)||'[]')}catch(e){}
function mount(){let anchor=document.getElementById('shadowingHub')||document.getElementById('podcastEpisodeHub')||document.getElementById('listening')||document.querySelector('.sec');if(!anchor||document.getElementById('jlptListeningExam'))return;let d=document.createElement('div');d.id='jlptListeningExam';d.innerHTML='<div class="le-row"><b>🎧 JLPT 聴解（ちょうかい）考试模式</b><select id="leLv"><option>N2</option><option>N3</option></select><select id="leType"></select></div><div class="le-meta" id="leStat"></div><div class="le-q"><div id="leAsk"></div><div class="le-actions" style="margin-top:9px"><button id="lePlay">▶ 播放听力</button><button id="leReplay">↻ 再听一次</button></div><div id="leOpts" class="le-opts"></div><div id="leExplain" class="le-hidden"></div></div><div class="le-actions"><button id="leNext">下一题 →</button><button id="leScript">答题后查看原文/解析</button></div>';anchor.parentNode.insertBefore(d,anchor);let cur=null,answered=false;const lv=d.querySelector('#leLv'),ty=d.querySelector('#leType');
function types(){let a=[...new Set(Q.filter(x=>x.l===lv.value).map(x=>x.t))];ty.innerHTML='<option value="全部">全部题型</option>'+a.map(x=>'<option>'+x+'</option>').join('')}
function pool(){return Q.filter(x=>x.l===lv.value&&(ty.value==='全部'||x.t===ty.value))}
function next(){let p=pool(),fresh=p.filter(x=>!seen.includes(x.id));if(!fresh.length){seen=seen.filter(id=>!p.some(x=>x.id===id));fresh=p}cur=fresh[Math.floor(Math.random()*fresh.length)];answered=false;d.querySelector('#leAsk').innerHTML='<b>'+cur.t+'</b><br>'+cur.ask;d.querySelector('#leOpts').innerHTML=cur.opts.map((o,i)=>'<button data-i="'+i+'">'+(i+1)+'. '+o+'</button>').join('');d.querySelector('#leExplain').className='le-hidden';d.querySelector('#leExplain').textContent='';d.querySelectorAll('#leOpts button').forEach(b=>b.onclick=()=>answer(+b.dataset.i,b));d.querySelector('#leStat').textContent='题库 '+p.length+'｜已做 '+p.filter(x=>seen.includes(x.id)).length+'｜错题 '+wrong.length}
function play(){if(!cur)return;if(typeof playBackgroundJapanese==='function')playBackgroundJapanese(cur.text,1,'JLPT 聴解 · '+cur.t);else if('speechSynthesis'in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(cur.text);u.lang='ja-JP';speechSynthesis.speak(u)}}
function answer(i,b){if(answered)return;answered=true;d.querySelectorAll('#leOpts button').forEach(x=>x.disabled=true);if(i===cur.a)b.classList.add('le-ok');else{b.classList.add('le-no');d.querySelectorAll('#leOpts button')[cur.a].classList.add('le-ok');if(!wrong.includes(cur.id))wrong.push(cur.id)}if(!seen.includes(cur.id))seen.push(cur.id);localStorage.setItem(SEEN,JSON.stringify(seen));localStorage.setItem(WRONG,JSON.stringify(wrong));d.querySelector('#leExplain').className='';d.querySelector('#leExplain').innerHTML='<hr><b>原文</b><br>'+cur.text+'<br><br><b>解析</b><br>'+cur.why}
d.querySelector('#lePlay').onclick=play;d.querySelector('#leReplay').onclick=play;d.querySelector('#leNext').onclick=next;d.querySelector('#leScript').onclick=()=>{if(answered)d.querySelector('#leExplain').className='';else d.querySelector('#leExplain').textContent='先作答，再显示原文和解析。'};lv.onchange=()=>{types();next()};ty.onchange=next;types();next()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();setTimeout(mount,650)})();<\/script>`;return h.replace('</body>',js+'</body>')}catch(e){return h}};