window.applyMatureModulesPatch=function(h){try{if(!h||h.includes('data-mature-modules="1"'))return h;
const css=`<style data-mature-modules="1">
#matureReviewHub{margin:16px 0;padding:15px;border:1px solid rgba(255,255,255,.13);border-radius:20px;background:rgba(255,255,255,.04)}
.mm-head,.mm-actions,.mm-stats{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.mm-actions button{flex:1;min-width:100px;min-height:44px}.mm-stats span{padding:4px 9px;border-radius:999px;background:rgba(255,255,255,.08);font-size:13px}
.mm-card{margin-top:12px;padding:14px;border-radius:16px;background:rgba(255,255,255,.05)}.mm-q{font-size:22px;font-weight:800;line-height:1.6}.mm-a{margin-top:10px;line-height:1.8}.mm-hidden{display:none!important}
#mmQuizOpts button{display:block;width:100%;margin:7px 0;min-height:42px;text-align:left}
@media(max-width:560px){.mm-actions{display:grid;grid-template-columns:1fr 1fr}.mm-q{font-size:19px}}
</style>`;
h=h.replace('</head>',css+'</head>');
const js=`<script data-mature-modules="1">(()=>{const K='jlpt_vocab_recognition_v1',LOG='jlpt_srs_log_v2',DAY=86400000;
const load=()=>{try{return JSON.parse(localStorage.getItem(K)||'{}')}catch(e){return {}}},save=x=>localStorage.setItem(K,JSON.stringify(x));
function iv(r,n){if(r==='again')return 10*60*1000;if(r==='hard')return Math.max(DAY,(n||1)*DAY);if(r==='easy')return Math.min(90*DAY,Math.max(7*DAY,(n||1)*7*DAY));return Math.min(60*DAY,Math.max(3*DAY,(n||1)*3*DAY))}
function mount(){let sec=document.getElementById('review');if(!sec||document.getElementById('matureReviewHub'))return;let hub=document.createElement('div');hub.id='matureReviewHub';hub.innerHTML='<div class="mm-head"><b>🧠 到期复习 · SRS</b><span>参考成熟 Again / Hard / Good / Easy 流程</span></div><div class="mm-stats" id="mmStats"></div><div class="mm-card"><div class="mm-q" id="mmQ">今天没有到期单词 🎉</div><div class="mm-a mm-hidden" id="mmA"></div><div class="mm-actions" style="margin-top:12px"><button id="mmReveal">显示答案</button><button data-r="again">Again 忘记</button><button data-r="hard">Hard 模糊</button><button data-r="good">Good 认识</button><button data-r="easy">Easy 熟练</button></div></div><div class="mm-card"><b>🎯 多方向测试</b><div id="mmQuizQ" style="margin-top:8px"></div><div id="mmQuizOpts"></div><button id="mmNextQuiz">换一题</button></div>';sec.insertBefore(hub,sec.firstChild);
let cur=null;function due(){let d=load(),now=Date.now();return Object.entries(d).filter(([k,x])=>(x.nextReview||0)<=now).sort((a,b)=>(a[1].nextReview||0)-(b[1].nextReview||0))}
function render(){let d=load(),a=due(),vals=Object.values(d);document.getElementById('mmStats').innerHTML='<span>到期 '+a.length+'</span><span>总学习 '+vals.length+'</span><span>困难 '+vals.filter(x=>x.state==='forgot'||x.state==='fuzzy').length+'</span>';cur=a[0]||null;let q=document.getElementById('mmQ'),ans=document.getElementById('mmA');if(!cur){q.textContent='今天没有到期单词 🎉';ans.textContent='';return}q.textContent=cur[1].word;ans.textContent='等级：'+(cur[1].level||'—')+' · 上次：'+(cur[1].state==='forgot'?'忘记':cur[1].state==='fuzzy'?'模糊':'认识');ans.classList.add('mm-hidden')}
document.getElementById('mmReveal').onclick=()=>document.getElementById('mmA').classList.remove('mm-hidden');hub.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{if(!cur)return;let d=load(),x=d[cur[0]],r=b.dataset.r,n=(x.srsStep||0)+(r==='again'?0:1);x.srsStep=n;x.state=r==='again'?'forgot':r==='hard'?'fuzzy':'known';x.lastRating=r;x.updatedAt=Date.now();x.nextReview=Date.now()+iv(r,n);d[cur[0]]=x;save(d);try{let l=JSON.parse(localStorage.getItem(LOG)||'[]');l.push({k:cur[0],r,t:Date.now()});localStorage.setItem(LOG,JSON.stringify(l.slice(-1000)))}catch(e){}render();quiz()});
function quiz(){let vals=Object.values(load()).filter(x=>x.word);let box=document.getElementById('mmQuizOpts'),q=document.getElementById('mmQuizQ');if(vals.length<4){q.textContent='学习至少 4 个单词后自动开启测试。';box.innerHTML='';return}let x=vals[Math.floor(Math.random()*vals.length)],others=vals.filter(y=>y.word!==x.word).sort(()=>Math.random()-.5).slice(0,3),opts=[x,...others].sort(()=>Math.random()-.5);q.textContent='哪一个是你最近标记为「'+(x.state==='forgot'?'忘记':x.state==='fuzzy'?'模糊':'认识')+'」的词？';box.innerHTML=opts.map(o=>'<button data-w="'+encodeURIComponent(o.word)+'">'+o.word+'</button>').join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{b.textContent+=(decodeURIComponent(b.dataset.w)===x.word?' ✓':' ✗')})}
document.getElementById('mmNextQuiz').onclick=quiz;render();quiz()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();setTimeout(mount,600)})();<\/script>`;
return h.replace('</body>',js+'</body>')}catch(e){return h}};
